int pinLed = 13; //Membuat variabel untuk LED

int pinBtn = 9; // Membuat variabel untuk Button
 
void setup() {
 pinMode(pinLed, OUTPUT); // variabel pinLed menjadi output
 pinMode(pinBtn, INPUT_PULLUP); // variabel pinBtn menjadi input
}
 
void loop() {
 
  // variabel statusBtn menyimpan nilai dari hasil pembacaan pinBtn
  int  statusBtn = digitalRead(pinBtn);
 
  // Ketika push button tidak ditekan nilainya HIGH/1
  if(statusBtn == HIGH)
    {
      digitalWrite(pinLed, LOW);
      
    } else {
      digitalWrite(pinLed, HIGH);
      delay(1000);
      digitalWrite(pinLed, LOW);
      delay(750);
      digitalWrite(pinLed, HIGH);
      delay(750);
      digitalWrite(pinLed, LOW);
      delay(500);
      digitalWrite(pinLed, HIGH);
      delay(500);
      digitalWrite(pinLed, LOW);
      delay(250);
      digitalWrite(pinLed, HIGH);
      delay(250);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(50);
      digitalWrite(pinLed, HIGH);
      delay(50);
      digitalWrite(pinLed, LOW);
      delay(1000);
      digitalWrite(pinLed, HIGH);
      delay(1000);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(1000);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(1000);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(1000);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(1000);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(100);
      digitalWrite(pinLed, LOW);
      delay(100);
      digitalWrite(pinLed, HIGH);
      delay(1000);
    }
}
